package br.senai.informatica.leansurvey.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answerquestion generated by hbm2java
 */
@Entity
@Table(name = "answerquestion", catalog = "leansurvey")
public class Answerquestion implements java.io.Serializable {

	private Long id;
	private Question question;
	private Questionnaireanswer questionnaireanswer;
	private Integer answerInt;
	private String answerString;

	public Answerquestion() {
	}

	public Answerquestion(Question question, Questionnaireanswer questionnaireanswer) {
		this.question = question;
		this.questionnaireanswer = questionnaireanswer;
	}

	public Answerquestion(Question question, Questionnaireanswer questionnaireanswer, Integer answerInt,
			String answerString) {
		this.question = question;
		this.questionnaireanswer = questionnaireanswer;
		this.answerInt = answerInt;
		this.answerString = answerString;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "QuestionId", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "QuestionnaireAnswerId", nullable = false)
	public Questionnaireanswer getQuestionnaireanswer() {
		return this.questionnaireanswer;
	}

	public void setQuestionnaireanswer(Questionnaireanswer questionnaireanswer) {
		this.questionnaireanswer = questionnaireanswer;
	}

	@Column(name = "AnswerInt")
	public Integer getAnswerInt() {
		return this.answerInt;
	}

	public void setAnswerInt(Integer answerInt) {
		this.answerInt = answerInt;
	}

	@Column(name = "AnswerString", length = 100)
	public String getAnswerString() {
		return this.answerString;
	}

	public void setAnswerString(String answerString) {
		this.answerString = answerString;
	}

}
