package br.senai.informatica.leansurvey.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Condition generated by hbm2java
 */
@Entity
@Table(name = "condition", catalog = "leansurvey")
public class Condition implements java.io.Serializable {

	private Long id;
	private String description;
	//private Set questionrules = new HashSet(0);

	public Condition() {
	}

	public Condition(String description) {
		this.description = description;
	}
/*
	public Condition(String description, Set questionrules) {
		this.description = description;
		this.questionrules = questionrules;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "condition")
	public Set getQuestionrules() {
		return this.questionrules;
	}

	public void setQuestionrules(Set questionrules) {
		this.questionrules = questionrules;
	}*/

}
