package br.senai.informatica.leansurvey.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gender generated by hbm2java
 */
@Entity
@Table(name = "gender", catalog = "leansurvey")
public class Gender implements java.io.Serializable {

	private long id;
	private String description;
	//private Set interviewers = new HashSet(0);

	public Gender() {
	}

	public Gender(String description) {
		this.description = description;
	}

	/*public Gender(String description, Set interviewers) {
		this.description = description;
		this.interviewers = interviewers;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "gender")
	public Set getInterviewers() {
		return this.interviewers;
	}

	public void setInterviewers(Set interviewers) {
		this.interviewers = interviewers;
	}*/

}
