package br.senai.informatica.leansurvey.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Interviewer generated by hbm2java
 */
@Entity
@Table(name = "interviewer", catalog = "leansurvey")
public class Interviewer implements java.io.Serializable {

	private Long id;
	private Gender gender;
	private String name;
	private String username;
	private String password;
	private String salt;
	private String email;
	private Date birthday;
	private String cpf;
	private String contactNumber;
	//private Set questionnaireanswers = new HashSet(0);

	public Interviewer() {
	}

	public Interviewer(Gender gender, String name, String username, String password, String salt, String email,
			Date birthday, String cpf, String contactNumber) {
		this.gender = gender;
		this.name = name;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.email = email;
		this.birthday = birthday;
		this.cpf = cpf;
		this.contactNumber = contactNumber;
	}

	/*public Interviewer(Gender gender, String name, String username, String password, String salt, String email,
			Date birthday, String cpf, String contactNumber, Set questionnaireanswers) {
		this.gender = gender;
		this.name = name;
		this.username = username;
		this.password = password;
		this.salt = salt;
		this.email = email;
		this.birthday = birthday;
		this.cpf = cpf;
		this.contactNumber = contactNumber;
		this.questionnaireanswers = questionnaireanswers;
	}
*/
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "GenderId", nullable = false)
	public Gender getGender() {
		return this.gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Username", nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 12)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Salt", nullable = false, length = 50)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "Email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(style = "yyyy-MM-dd")
	@Column(name = "Birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "CPF", nullable = false, length = 12)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "ContactNumber", nullable = false, length = 15)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewer")
	public Set getQuestionnaireanswers() {
		return this.questionnaireanswers;
	}

	public void setQuestionnaireanswers(Set questionnaireanswers) {
		this.questionnaireanswers = questionnaireanswers;
	}*/

}
