package br.senai.informatica.leansurvey.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questiontype generated by hbm2java
 */
@Entity
@Table(name = "questiontype", catalog = "leansurvey")
public class Questiontype implements java.io.Serializable {

	private Long id;
	private String description;

	public Questiontype() {
	}

	public Questiontype(String description) {
		this.description = description;
	}

	public Questiontype(String description, Set questions) {
		this.description = description;
	}

	
	
	public Questiontype(Long id, String description) {
		super();
		this.id = id;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}
