package br.senai.informatica.leansurvey.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questionrulegroup generated by hbm2java
 */
@Entity
@Table(name = "questionrulegroup", catalog = "leansurvey")
public class Questionrulegroup implements java.io.Serializable {

	private Long id;
	private Question question;
	//private Set questionrules = new HashSet(0);

	public Questionrulegroup() {
	}

	public Questionrulegroup(Question question) {
		this.question = question;
	}

	/*public Questionrulegroup(Question question, Set questionrules) {
		this.question = question;
		this.questionrules = questionrules;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "QuestionId", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionrulegroup")
	public Set getQuestionrules() {
		return this.questionrules;
	}

	public void setQuestionrules(Set questionrules) {
		this.questionrules = questionrules;
	}
*/
}
