package br.senai.informatica.leansurvey.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Questionnaire generated by hbm2java
 */
@Entity
@Table(name = "questionnaire", catalog = "leansurvey")
public class Questionnaire implements java.io.Serializable {

	private Long id;
	private Employee employee;
	private Enterprise enterprise;
	private String title;
	private String description;
	private BigDecimal interviewerPayment;
	private Date startDate;
	private Date endDate;
	private int limite;
	//private Set questionnaireanswers = new HashSet(0);
	//private Set questions = new HashSet(0);

	public Questionnaire() {
	}

	public Questionnaire(Employee employee, Enterprise enterprise, String title, String description,
			BigDecimal interviewerPayment, int limite) {
		this.employee = employee;
		this.enterprise = enterprise;
		this.title = title;
		this.description = description;
		this.interviewerPayment = interviewerPayment;
		this.limite = limite;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EmployeeId", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EnterpriseId", nullable = false)
	public Enterprise getEnterprise() {
		return this.enterprise;
	}

	public void setEnterprise(Enterprise enterprise) {
		this.enterprise = enterprise;
	}

	@Column(name = "Title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "InterviewerPayment", nullable = false, precision = 5)
	public BigDecimal getInterviewerPayment() {
		return this.interviewerPayment;
	}

	public void setInterviewerPayment(BigDecimal interviewerPayment) {
		this.interviewerPayment = interviewerPayment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "StartDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EndDate", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "Limite", nullable = false)
	public int getLimite() {
		return this.limite;
	}

	public void setLimite(int limite) {
		this.limite = limite;
	}

	/* @OneToMany(fetch = FetchType.LAZY, mappedBy = "questionnaire")
	public Set getQuestionnaireanswers() {
		return this.questionnaireanswers;
	}

	public void setQuestionnaireanswers(Set questionnaireanswers) {
		this.questionnaireanswers = questionnaireanswers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionnaire")
	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}
    */
}
